export const STORAGE_KEY = {
	ACCESS_TOKEN: "AT_DATA",
	REFRESH_TOKEN: "RT_DATA",
	ID: "BENEFIT_ID",
} as const;

export const STORAGE_KEY_ADMIN = {
	ACCESS_TOKEN: "AD_AT_DATA",
	REFRESH_TOKEN: "AD_RT_DATA",
	MEM_NM: "MEM_NM",
	USER_TYPE: "USER_TYPE",
	CO_NO: "CO_NO",
	CO_NM: "CO_NM",
	ORGN_NM: "ORGN_NM",
	MEM_NO: "MEM_NO",
	EVNT_NO: "EVNT_NO",
	EVNT_NM: "EVNT_NM",
	ID: "ID",
} as const;

export const STORAGE_KEY_RETURN_URL = {
	URL: "RETURN_URL",
} as const;

export const PAGE_URL = {
	LOGIN_ADMIN: "/login",
};

export const APIRETURN_CODE = {
	SUCCESS: "0000",
	CANTFIND: "0802",
	NOTFOUND: "0803",
	EVNTNOTFOUND: "E001",
	ADMIN_ACCESS_TOKEN: "AD_AT_DATA",
	ADMIN_REFRESH_TOKEN: "AD_RT_DATA",
	ALREADY_SUCCESS: "0001",
	EXPIRATION_OR_EMPTY: "0002",
	OTHER_AL_SUCCESS: "0004",
	ORDER_FAILED: "0407",
} as const;

export const API_TOKKEN_ERR_CODE = {
	TOKEN_ERR_EXPIRE: "T001",
	TOKEN_ERR_NO_TOKEN: "T002",
	TOKEN_ERR_NO_REDIS: "T003",
	TOKEN_ERR_CHANGE: "T004",
	TOKEN_ERR_AUTH: "T005",
} as const;
